;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	))

(setq mc/cmds-to-run-once
      '(
	describe-variable
	helm-M-x
	hungry-delete-backward
	hydra--negative-argument
	hydra-multiple-cursors/mc/mark-next-like-this
	hydra-multiple-cursors/mc/mark-next-like-this-word
	hydra-multiple-cursors/mc/mark-previous-like-this
	hydra-multiple-cursors/mc/skip-to-next-like-this
	hydra-multiple-cursors/mc/skip-to-previous-like-this
	hydra-multiple-cursors/mc/unmark-next-like-this
	hydra-multiple-cursors/mc/unmark-previous-like-this
	))
